export type Stage = {
  id: number;
  title: string;
  videoUrl: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
};

export type LearningContent = {
  [key: string]: Stage[];
};

export const learningContent: LearningContent = {
  sports: [
    {
      id: 1,
      title: 'Cricket Shots',
      videoUrl: 'https://videos.pexels.com/video-files/5243396/5243396-sd_540_960_25fps.mp4',
      question: 'What type of shot did the batsman use?',
      options: ['Low ground', 'Upper cut', 'Pull shot', 'Shoulder-above lofted shot'],
      correctAnswerIndex: 3,
    },
    {
      id: 2,
      title: 'Basketball Skills',
      videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-sd_640_360_30fps.mp4',
      question: 'What skill is shown in this clip?',
      options: ['Heading', 'Dribbling', 'Tackling', 'Goalkeeping'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'Scoring in Basketball',
      videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-sd_640_360_30fps.mp4',
      question: 'What is this scoring method called?',
      options: ['Dunk', 'Layup', 'Free throw', 'Pass shot'],
      correctAnswerIndex: 1,
    },
    {
      id: 4,
      title: 'Track and Field',
      videoUrl: 'https://videos.pexels.com/video-files/8009257/8009257-sd_640_360_25fps.mp4',
      question: 'What position are they in?',
      options: ['Ready position', 'Jump stance', 'Starting blocks position', 'Relaxed jog'],
      correctAnswerIndex: 2,
    },
    {
      id: 5,
      title: 'Tennis Techniques',
      videoUrl: 'https://videos.pexels.com/video-files/7990150/7990150-sd_640_360_25fps.mp4',
      question: 'What is the gentle shot near net?',
      options: ['Smash', 'Drop shot', 'Clear', 'Drive'],
      correctAnswerIndex: 1,
    },
  ],
  science: [
    {
      id: 1,
      title: 'States of Matter',
      videoUrl: 'https://videos.pexels.com/video-files/856950/856950-sd_640_360_25fps.mp4',
      question: 'What change is happening?',
      options: ['Freezing', 'Evaporation', 'Melting', 'Cooling'],
      correctAnswerIndex: 2,
    },
    {
      id: 2,
      title: 'Forces in Nature',
      videoUrl: 'https://videos.pexels.com/video-files/3014019/3014019-sd_640_360_24fps.mp4',
      question: 'Which force is shown?',
      options: ['Gravity', 'Magnetic force', 'Friction', 'Electric force'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'Plant Biology',
      videoUrl: 'https://videos.pexels.com/video-files/855301/855301-sd_640_360_30fps.mp4',
      question: 'Plant responds to?',
      options: ['Water', 'Light', 'Heat', 'Sound'],
      correctAnswerIndex: 1,
    },
    {
      id: 4,
      title: 'Chemical Changes',
      videoUrl: 'https://videos.pexels.com/video-files/5473641/5473641-sd_640_360_25fps.mp4',
      question: 'Burning is?',
      options: ['Physical', 'Chemical', 'Melting', 'Freezing'],
      correctAnswerIndex: 1,
    },
    {
      id: 5,
      title: 'The Human Brain',
      videoUrl: 'https://videos.pexels.com/video-files/8468700/8468700-sd_640_360_25fps.mp4',
      question: 'Which part of the brain is responsible for memory?',
      options: ['Cerebellum', 'Hippocampus', 'Frontal Lobe', 'Brain Stem'],
      correctAnswerIndex: 1,
    },
  ],
  english: [
    {
      id: 1,
      title: 'Parts of Speech: Nouns',
      videoUrl: 'https://videos.pexels.com/video-files/6124238/6124238-sd_640_360_25fps.mp4',
      question: 'Which is a noun?',
      options: ['Jump', 'Quickly', 'Table', 'Red'],
      correctAnswerIndex: 2,
    },
    {
      id: 2,
      title: 'Parts of Speech: Verbs',
      videoUrl: 'https://videos.pexels.com/video-files/7578189/7578189-sd_640_360_25fps.mp4',
      question: 'Verb in action?',
      options: ['Child', 'Running', 'Field', 'Big'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'Parts of Speech: Pronouns',
      videoUrl: 'https://videos.pexels.com/video-files/5793946/5793946-sd_640_360_25fps.mp4',
      question: "'He' is?",
      options: ['Noun', 'Verb', 'Pronoun', 'Article'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'Understanding Tense',
      videoUrl: 'https://videos.pexels.com/video-files/10065306/10065306-sd_540_960_25fps.mp4',
      question: 'Tense?',
      options: ['Past', 'Future', 'Present', 'None'],
      correctAnswerIndex: 2,
    },
    {
      id: 5,
      title: 'Reading Comprehension',
      videoUrl: 'https://videos.pexels.com/video-files/4325026/4325026-sd_640_360_25fps.mp4',
      question: 'Main idea?',
      options: ['Friendship', 'Animals', 'Weather', 'Travel'],
      correctAnswerIndex: 0,
    },
  ],
  creativity: [
    {
      id: 1,
      title: 'Art Forms',
      videoUrl: 'https://videos.pexels.com/video-files/7036361/7036361-sd_640_360_25fps.mp4',
      question: 'This art is?',
      options: ['Painting', 'Origami', 'Sketching', 'Embroidery'],
      correctAnswerIndex: 1,
    },
    {
      id: 2,
      title: 'Art Examples',
      videoUrl: 'https://videos.pexels.com/video-files/7541604/7541604-sd_640_360_25fps.mp4',
      question: 'Example of?',
      options: ['Drawing', 'Dance', 'Modeling', 'Sewing'],
      correctAnswerIndex: 2,
    },
    {
      id: 3,
      title: 'Understanding Dance',
      videoUrl: 'https://videos.pexels.com/video-files/5380590/5380590-sd_640_360_25fps.mp4',
      question: 'Dance involves?',
      options: ['Eating', 'Sleeping', 'Rhythm & movement', 'Math'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'Cinematography',
      videoUrl: 'https://videos.pexels.com/video-files/7127301/7127301-sd_640_360_25fps.mp4',
      question: 'This shot is?',
      options: ['Long shot', 'Close-up', 'Wide shot', 'Side shot'],
      correctAnswerIndex: 1,
    },
    {
      id: 5,
      title: 'Forms of Art',
      videoUrl: 'https://videos.pexels.com/video-files/3253509/3253509-sd_640_360_30fps.mp4',
      question: 'Art form?',
      options: ['Painting', 'Carving', 'Dancing', 'Poetry'],
      correctAnswerIndex: 1,
    },
  ],
  social: [
    {
      id: 1,
      title: 'Traffic Rules',
      videoUrl: 'https://videos.pexels.com/video-files/8295286/8295286-sd_640_360_25fps.mp4',
      question: 'Red light means?',
      options: ['Go', 'Stop', 'Turn', 'Park'],
      correctAnswerIndex: 1,
    },
    {
      id: 2,
      title: 'Community Helpers',
      videoUrl: 'https://videos.pexels.com/video-files/6755490/6755490-sd_640_360_25fps.mp4',
      question: 'He is a?',
      options: ['Teacher', 'Firefighter', 'Doctor', 'Chef'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'Famous Landmarks',
      videoUrl: 'https://videos.pexels.com/video-files/5598335/5598335-sd_640_360_25fps.mp4',
      question: 'This is a?',
      options: ['River', 'Mountain', 'Monument', 'Forest'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'Weather Conditions',
      videoUrl: 'https://videos.pexels.com/video-files/5529124/5529124-sd_640_360_24fps.mp4',
      question: 'Weather shown?',
      options: ['Sunny', 'Rainy', 'Snowy', 'Cloudy'],
      correctAnswerIndex: 1,
    },
    {
      id: 5,
      title: 'Areas of Life',
      videoUrl: 'https://videos.pexels.com/video-files/9869150/9869150-sd_640_360_25fps.mp4',
      question: 'This is part of?',
      options: ['Sports', 'Democracy', 'Cooking', 'Art'],
      correctAnswerIndex: 1,
    },
  ],
  math: [
    {
      id: 1,
      title: 'Counting',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'How many apples?',
      options: ['2', '3', '4', '5'],
      correctAnswerIndex: 1,
    },
    {
      id: 2,
      title: 'Geometry: Shapes',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'Which shape rolls easily?',
      options: ['Cube', 'Sphere', 'Cylinder', 'Cone'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'Geometry: Symmetry',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'Symmetrical sides?',
      options: ['1', '2', '3', 'None'],
      correctAnswerIndex: 1,
    },
    {
      id: 4,
      title: 'Geometry: Angles',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'Angle shown?',
      options: ['Acute', 'Obtuse', 'Right', 'Straight'],
      correctAnswerIndex: 0,
    },
    {
      id: 5,
      title: 'Probability',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'Probability heads?',
      options: ['0', '1', '1/2', '1/4'],
      correctAnswerIndex: 2,
    },
  ],
};
