export type Stage = {
  id: number;
  title: string;
  videoUrl: string;
  question: string;
  options: string[];
  correctAnswerIndex: number;
};

export type LearningContent = {
  [key: string]: Stage[];
};

export const learningContent: LearningContent = {
  sports: [
    {
      id: 1,
      title: 'The Rules of Basketball',
      videoUrl: 'https://videos.pexels.com/video-files/3209828/3209828-sd_640_360_30fps.mp4',
      question: 'How many players are on a basketball court for one team?',
      options: ['5', '6', '7', '11'],
      correctAnswerIndex: 0,
    },
    {
      id: 2,
      title: 'The Perfect Soccer Kick',
      videoUrl: 'https://videos.pexels.com/video-files/5370640/5370640-sd_640_360_25fps.mp4',
      question: 'What part of the foot is ideal for a powerful shot?',
      options: ['Toes', 'Heel', 'Laces', 'Inside'],
      correctAnswerIndex: 2,
    },
    {
      id: 3,
      title: 'Swimming Strokes 101',
      videoUrl: 'https://videos.pexels.com/video-files/8009257/8009257-sd_640_360_25fps.mp4',
      question: 'Which stroke is performed on the back?',
      options: ['Freestyle', 'Breaststroke', 'Backstroke', 'Butterfly'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'The Art of the Home Run',
      videoUrl: 'https://videos.pexels.com/video-files/5243396/5243396-sd_540_960_25fps.mp4',
      question: 'What is it called when a batter hits the ball out of the park?',
      options: ['A Strike', 'A Home Run', 'A Foul Ball', 'A Base Hit'],
      correctAnswerIndex: 1,
    },
    {
      id: 5,
      title: 'Tennis Serve Technique',
      videoUrl: 'https://videos.pexels.com/video-files/7990150/7990150-sd_640_360_25fps.mp4',
      question: 'A game of tennis begins with what action?',
      options: ['Rally', 'Volley', 'Serve', 'Smash'],
      correctAnswerIndex: 2,
    },
  ],
  science: [
    {
      id: 1,
      title: 'The Solar System',
      videoUrl: 'https://videos.pexels.com/video-files/3014019/3014019-sd_640_360_24fps.mp4',
      question: 'Which planet is known as the Red Planet?',
      options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
      correctAnswerIndex: 1,
    },
    {
      id: 2,
      title: 'The Water Cycle',
      videoUrl: 'https://videos.pexels.com/video-files/856950/856950-sd_640_360_25fps.mp4',
      question: 'What is the process of water turning into vapor?',
      options: ['Condensation', 'Precipitation', 'Evaporation', 'Collection'],
      correctAnswerIndex: 2,
    },
    {
      id: 3,
      title: 'Chemical Reactions',
      videoUrl: 'https://videos.pexels.com/video-files/5473641/5473641-sd_640_360_25fps.mp4',
      question: 'What is a common sign of a chemical reaction?',
      options: ['Change in shape', 'Change in color', 'Change in size', 'Change in location'],
      correctAnswerIndex: 1,
    },
    {
      id: 4,
      title: 'Photosynthesis',
      videoUrl: 'https://videos.pexels.com/video-files/855301/855301-sd_640_360_30fps.mp4',
      question: 'What do plants use to convert sunlight into energy?',
      options: ['Water', 'Oxygen', 'Chlorophyll', 'Carbon Dioxide'],
      correctAnswerIndex: 2,
    },
    {
      id: 5,
      title: 'The Human Brain',
      videoUrl: 'https://videos.pexels.com/video-files/8468700/8468700-sd_640_360_25fps.mp4',
      question: 'Which part of the brain is responsible for memory?',
      options: ['Cerebellum', 'Hippocampus', 'Frontal Lobe', 'Brain Stem'],
      correctAnswerIndex: 1,
    },
  ],
  english: [
    {
      id: 1,
      title: 'Understanding Nouns',
      videoUrl: 'https://videos.pexels.com/video-files/6124238/6124238-sd_640_360_25fps.mp4',
      question: 'What does a noun refer to?',
      options: ['An action', 'A description', 'A person, place, or thing', 'A connecting word'],
      correctAnswerIndex: 2,
    },
    {
      id: 2,
      title: 'The Power of Verbs',
      videoUrl: 'https://videos.pexels.com/video-files/7578189/7578189-sd_640_360_25fps.mp4',
      question: 'Which word in "The cat sleeps" is the verb?',
      options: ['The', 'cat', 'sleeps', 'None of the above'],
      correctAnswerIndex: 2,
    },
    {
      id: 3,
      title: 'Crafting Adjectives',
      videoUrl: 'https://videos.pexels.com/video-files/5793946/5793946-sd_640_360_25fps.mp4',
      question: 'Adjectives are used to describe what?',
      options: ['Verbs', 'Nouns', 'Adverbs', 'Pronouns'],
      correctAnswerIndex: 1,
    },
    {
      id: 4,
      title: 'Shakespearean Sonnets',
      videoUrl: 'https://videos.pexels.com/video-files/10065306/10065306-sd_540_960_25fps.mp4',
      question: 'How many lines does a sonnet have?',
      options: ['10', '12', '14', '16'],
      correctAnswerIndex: 2,
    },
    {
      id: 5,
      title: 'The Hero\'s Journey',
      videoUrl: 'https://videos.pexels.com/video-files/4325026/4325026-sd_640_360_25fps.mp4',
      question: 'What is the first step in a typical hero\'s journey?',
      options: ['The Reward', 'The Ordeal', 'The Call to Adventure', 'The Return Home'],
      correctAnswerIndex: 2,
    },
  ],
  creativity: [
    {
      id: 1,
      title: 'The Color Wheel',
      videoUrl: 'https://videos.pexels.com/video-files/7036361/7036361-sd_640_360_25fps.mp4',
      question: 'Which of these is a primary color?',
      options: ['Green', 'Orange', 'Blue', 'Purple'],
      correctAnswerIndex: 2,
    },
    {
      id: 2,
      title: 'Basic Drawing Techniques',
      videoUrl: 'https://videos.pexels.com/video-files/7541604/7541604-sd_640_360_25fps.mp4',
      question: 'What is "shading" used for in drawing?',
      options: ['To add color', 'To create the illusion of form and light', 'To outline the subject', 'To erase mistakes'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'The Elements of Music',
      videoUrl: 'https://videos.pexels.com/video-files/5380590/5380590-sd_640_360_25fps.mp4',
      question: 'What is the "tempo" of a piece of music?',
      options: ['The volume', 'The key', 'The speed', 'The instruments used'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'Digital Art Tools',
      videoUrl: 'https://videos.pexels.com/video-files/7127301/7127301-sd_640_360_25fps.mp4',
      question: 'What is a common tool for digital painting?',
      options: ['A paintbrush', 'A stylus and tablet', 'A canvas', 'A charcoal stick'],
      correctAnswerIndex: 1,
    },
    {
      id: 5,
      title: 'Brainstorming Ideas',
      videoUrl: 'https://videos.pexels.com/video-files/3253509/3253509-sd_640_360_30fps.mp4',
      question: 'What is the main goal of brainstorming?',
      options: ['To generate a large quantity of ideas', 'To find the one perfect idea', 'To criticize ideas', 'To create a final plan'],
      correctAnswerIndex: 0,
    },
  ],
  social: [
    {
      id: 1,
      title: 'Ancient Egypt',
      videoUrl: 'https://videos.pexels.com/video-files/5598335/5598335-sd_640_360_25fps.mp4',
      question: 'What are the famous triangular structures in Egypt called?',
      options: ['Ziggurats', 'Temples', 'Pyramids', 'Castles'],
      correctAnswerIndex: 2,
    },
    {
      id: 2,
      title: 'The Roman Empire',
      videoUrl: 'https://videos.pexels.com/video-files/6755490/6755490-sd_640_360_25fps.mp4',
      question: 'What was the language of the Roman Empire?',
      options: ['Greek', 'Latin', 'Egyptian', 'English'],
      correctAnswerIndex: 1,
    },
    {
      id: 3,
      title: 'World Geography',
      videoUrl: 'https://videos.pexels.com/video-files/5529124/5529124-sd_640_360_24fps.mp4',
      question: 'How many continents are there?',
      options: ['5', '6', '7', '8'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'Types of Government',
      videoUrl: 'https://videos.pexels.com/video-files/8295286/8295286-sd_640_360_25fps.mp4',
      question: 'In a democracy, who holds the power?',
      options: ['The king', 'A dictator', 'The military', 'The people'],
      correctAnswerIndex: 3,
    },
    {
      id: 5,
      title: 'Cultural Traditions',
      videoUrl: 'https://videos.pexels.com/video-files/9869150/9869150-sd_640_360_25fps.mp4',
      question: 'What is a "tradition"?',
      options: ['A new law', 'A popular trend', 'A belief or behavior passed down within a group', 'A personal hobby'],
      correctAnswerIndex: 2,
    },
  ],
  math: [
    {
      id: 1,
      title: 'Basic Algebra',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'If x + 5 = 10, what is x?',
      options: ['2', '5', '10', '15'],
      correctAnswerIndex: 1,
    },
    {
      id: 2,
      title: 'The Pythagorean Theorem',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'The Pythagorean theorem applies to which type of triangle?',
      options: ['Equilateral', 'Isosceles', 'Scalene', 'Right-angled'],
      correctAnswerIndex: 3,
    },
    {
      id: 3,
      title: 'Understanding Fractions',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'What is 1/2 + 1/4?',
      options: ['2/6', '1/6', '3/4', '2/4'],
      correctAnswerIndex: 2,
    },
    {
      id: 4,
      title: 'The Concept of Pi',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'Pi (π) is the ratio of a circle\'s circumference to its...?',
      options: ['Area', 'Radius', 'Diameter', 'Chord'],
      correctAnswerIndex: 2,
    },
    {
      id: 5,
      title: 'Probability Basics',
      videoUrl: 'https://videos.pexels.com/video-files/8526550/8526550-sd_640_360_25fps.mp4',
      question: 'What is the probability of flipping a coin and getting heads?',
      options: ['100%', '75%', '50%', '25%'],
      correctAnswerIndex: 2,
    },
  ],
};
