// This file is automatically generated. Do not modify it manually.

import { FirebaseOptions } from 'firebase/app';

// Your web app's Firebase configuration
export const firebaseConfig: FirebaseOptions = {
  apiKey: "YOUR_API_KEY",
  authDomain: "codebharat-79c54.firebaseapp.com",
  projectId: "codebharat-79c54",
  storageBucket: "codebharat-79c54.appspot.com",
  messagingSenderId: "567406436329",
  appId: "1:567406436329:web:9c62c23579c54f4a34b22c"
};
